modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Mnesikos/Samhain/issues"
[[mods]]
modId="samhain" #mandatory
version="${file.jarVersion}"
displayName="Samhain"
displayURL="" #optional
logoFile=""
credits=""
authors="Mnesikos, Coda, Ikerleon, & Ashley"
description=""
[[dependencies.samhain]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
